### PR TITLE
Migrate mapping.launch to ros2

### LINKED ISSUE #5: convert mapping.launch to ROS2

### PR DESCRIPTION
**Pull request by SkiHatDuckie**
Resolves #5

`mapping.launch.py` successfully launches Rviz2, slam_toolbox, & teleop_twist_keyboard.

**Notes:**
It does NOT currently contain an Rviz2 config file, nor does it spawn a robot model to work with. These will be added in once I get to work on Gazebo inter-op.

Due to version incompatibilities with the stretch_ws, `teleop_twist.launch.py` and `mapping.yaml` have been manually migrated to ROS2 and moved to the stretch_seeing_eye_ros2 package.

xterm is now required to be installed on the system in order to launch `teleop_twist.launch.py`, due to teleop_twist_keyboard disliking running in the same terminal as the one it was launched from (throws a terminal error: unable to get a handle on `sys.stdin`) *(I would really like your thoughts on this note in particular)*

### CODE REVIEW

**Comment by varadn** [comment]
Great Work @SkiHatDuckie !! 

in regards to `teleop_twist.launch.py` have you tried to use the teleop given in the docs for ROS2 for stretch?

`ros2 run stretch_core keyboard_teleop` should work i tested this in the lab 
https://docs.hello-robot.com/0.3/ros2/robot_drivers/

make sure to launch `ros2 launch stretch_core stretch_driver.launch.py` to ensure that the stretch topics are being published

everything else with this pr looks fine to me but i will leave it unmerged until we can test it together in person.

**Comment by SkiHatDuckie** [comment]
I get this error when trying to build the stretch_ws. Maybe I'm using the wrong version of the repository?
image

**Comment by SkiHatDuckie** [comment]
Made some progress (cloning stretch_ros2 seemed to work), however, running the driver throws this error:

image

I think it needs the physical stretch robot in order to run, as I cannot find `stretch_body` anywhere.

**Comment by varadn** [comment]
ah i see where your confusion comes from. the `catkin` errors are due to you trying to run stretch_ws which is in ROS1. 

You need to run this code on the physical stretch for this to run or a working simulation. the stretch comes with a series of launch files in the package `stretch_core` that publish topics on the stretch

It's why i'm leaving this branch unmerged till we can test it on the actual stretch

**Comment by varadn** [comment]
i'm currently looking into `rviz2` as it is also causing issues for me

**Comment by varadn** [comment]
lgtm

**Pull request merged**
