### PR TITLE
Gazebo interop

### LINKED ISSUE #3: figure out Gazebo

### PR DESCRIPTION
**Pull request by SkiHatDuckie**
Resolves #3

In an attempt to reduce the number of top-level launch files needed to get things up and running, `robot_driver.launch.py` has been created. Now, only one launch command is needed in order to get the package up and running.

This also adds a README with docs on launching the package, as well as details for getting Gazebo inter-op set up.

### CODE REVIEW

**Comment by SkiHatDuckie** [comment]
I know that I can merge this myself now, but I just wanted to make sure everything looked good on your end.

**Comment by varadn** [comment]
i'll review this by tmr morning, but yea it's best practice to let repo owner to review PRs before merge

**Comment by varadn** [comment]
great work!

**Comment by varadn** [comment]
lgtm. from my understanding the stretch topics only get remapped when gazebo is launched

**Review by varadn — APPROVED** [review]

**Pull request merged**
